export const users = [
  {
    id: '1',
    name: 'Olexander Korotayev',
    role: 'Team lead',
    img: 'https://avatars.githubusercontent.com/u/116386768?v=4',
    ginHabLink: 'https://github.com/alexkorpol',
    LN_Link:
      'https://www.linkedin.com/in/олександр-коротаєв-5a985b275/',
    discription:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
  },
  {
    id: '2',
    name: 'Ivan Tymoshchuk',
    role: 'Deputy Team Leader',
    img: 'https://avatars.githubusercontent.com/u/116722310?v=4',
    ginHabLink: 'https://github.com/IvanTymoshchuk',
    LN_Link: 'https://www.linkedin.com/in/ivan-tymoshchuk-a00ab2262/',
    discription:
      'Enjoy what you do and you will never work in your life 👻',
  },
  {
    id: '3',
    name: 'Olia Medvetska',
    role: 'Scrum-master',
    img: 'https://avatars.githubusercontent.com/u/116505841?v=4',
    ginHabLink: 'https://github.com/Southernsunny',
    LN_Link: 'https://www.linkedin.com/in/olia-medvetska-4621a9261/',
    discription:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
  },
  {
    id: '4',
    name: 'Pavlo Antoniv',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/116433976?v=4',
    ginHabLink: 'https://github.com/PavloAntoniv',
    LN_Link: 'https://www.linkedin.com/in/pavlo-antoniv-7b553119a/',
    discription:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
  },
  {
    id: '5',
    name: 'Ruslan Zakharchuk',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/115725965?v=4',
    ginHabLink: 'https://github.com/ruslanzakhar',
    LN_Link: 'https://www.linkedin.com/',
    discription:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
  },
  {
    id: '6',
    name: 'Tonya Vaissberg',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/110049666?v=4',
    ginHabLink: 'https://github.com/Tonya-Pronina-Vaissberg',
    LN_Link: 'https://www.linkedin.com/in/tonya-pronina-39386a275/',
    discription:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
  },
  {
    id: '7',
    name: 'Maryna Cherkashina',
    role: 'Developer',
    img: '',
    ginHabLink: 'https://github.com/',
    LN_Link: 'https://www.linkedin.com/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: '8',
    name: 'Artem Sopilniak',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/91426417?v=4',
    ginHabLink: 'https://github.com/Doublebubble99',
    LN_Link: 'https://www.linkedin.com/',
    discription:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
  },
  {
    id: '9',
    name: 'Olexander Golub',
    role: 'Developer',
    img: 'https://avatars.githubusercontent.com/u/103257027?v=4',
    ginHabLink: 'https://github.com/Golub-Alexandr',
    LN_Link: 'https://www.linkedin.com/in/alexandr-golub-4331465b/',
    discription: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
  },
];

//     id: '1',
//     name: 'Гирич Роман',
//     role: 'Лідер команди',
//     img: 'https://avatars.githubusercontent.com/u/88936471?v=4',
//     ginHabLink: 'https://github.com/romanlancer/',
//     FB_Link: 'https://www.facebook.com/roman.girich',
//     LN_Link:
//       'https://www.linkedin.com/in/%D1%80%D0%BE%D0%BC%D0%B0%D0%BD-%D0%B3%D0%B8%D1%80%D0%B8%D1%87-1511bb226/',
//     discription:
//       'Шановні відвідувачі, вітаю Вас на нашому сайті кінофільмів, бажаю приємного перегляду та гарного настрою.',
//   },
//   {
//     id: '2',
//     name: 'Анна Ничик',
//     role: 'Scrum-мастер',
//     img: 'https://avatars.githubusercontent.com/u/88631065?v=4',
//     ginHabLink: 'https://github.com/AnnaNychyk',
//     FB_Link: 'https://www.facebook.com/profile.php?id=100014572051160',
//     LN_Link: 'https://www.linkedin.com/in/anna-nychyk-529061238/',
//     discription:
//       'Чудова командна робота. Усі люди в команді доброзичливі та відкриті. Допомогали один одному на всіх етапах роботи. Команда з якою хочеться працювати.',
//   },
//   {
//     id: '3',
//     name: 'Любов Данченко',
//     role: 'Розробник',
//     img: 'https://avatars.githubusercontent.com/u/22094005?v=4',
//     ginHabLink: 'https://github.com/LDanchenko',
//     FB_Link: 'https://www.facebook.com/profile.php?id=100013830070077',
//     LN_Link: 'https://www.linkedin.com/in/lubov-danchenko',
//     discription:
//       'Дякую нашій дружній команді за плідну і цікаву співпрацю, а також проекту GoIT за можливість прокачати свої знання в такому  проекті.',
//   },
//   {
//     id: '4',
//     name: 'Євген Ігнатенко',
//     role: 'Розробник',
//     img: 'https://avatars.githubusercontent.com/u/75755667?v=4',
//     ginHabLink: 'https://github.com/eijjeka',
//     FB_Link: 'https://www.facebook.com/',
//     LN_Link: 'https://www.linkedin.com/in/jekaignat/',
//     discription:
//       'Дуже приємний проект для цікавих людей, які хочуть переглянути доволі швидко про фільм все, що заманеться',
//   },
//   {
//     id: '5',
//     name: 'Вікторія Михальова',
//     role: 'Розробник',
//     img: 'https://avatars.githubusercontent.com/u/88782163?v=4',
//     ginHabLink: 'https://github.com/MViktoriia',
//     FB_Link: 'https://www.facebook.com/viktoriya.petrachkova',
//     LN_Link: 'https://www.linkedin.com/in/viktoriia-mykhalova-758b37237',
//     discription:
//       'Я дуже рада бути частиною цього проекту та нашої команди. Ми лише початківці у фронтенді, але ми завзято робимо все можливе, щоб допомогти клієнту досягти його бізнес-цілей, надаючи дійсно крутий продукт.',
//   },
//   {
//     id: '6',
//     name: 'Олександр Серебро',
//     role: 'Розробник',
//     img: 'https://avatars.githubusercontent.com/u/88261876?v=4',
//     ginHabLink: 'https://github.com/AlexSerebro',
//     FB_Link: 'https://www.facebook.com/',
//     LN_Link: 'https://www.linkedin.com/',
//     discription: 'Дуже приємно працювати в такій команді!!!',
//   },
//   {
//     id: '7',
//     name: 'Олександр Ніколаєнко',
//     role: 'Розробник',
//     img: 'https://avatars.githubusercontent.com/u/41318656?v=4',
//     ginHabLink: 'https://github.com/aleksander-nikolaenko',
//     FB_Link: 'https://www.facebook.com/',
//     LN_Link: 'https://www.linkedin.com/in/aleksander-nikolaienko-426b20229/',
//     discription:
//       'Я починаючий Full Stack розробник. Я закінчив курси з html та javascript. Продовжую вивчати фреймворки, такі як react.js та node.js.',
//   },
//   {
//     id: '8',
//     name: 'Сергій Сахно',
//     role: 'Розробник',
//     img: 'https://avatars.githubusercontent.com/u/89796587?v=4',
//     ginHabLink: 'https://github.com/SerhiiSakhno1994',
//     FB_Link: 'https://www.facebook.com/sergeysakhno1',
//     LN_Link: 'https://www.linkedin.com/in/serhii-sakhno-25934b229/',
//     discription: 'Привіт всім. Я студент GoIt. Над проектом працював у суперкоманді.',
//   },
//   {
//     id: '9',
//     name: 'Олександр Каширін',
//     role: 'Розробник',
//     img: 'https://avatars.githubusercontent.com/u/88508533?v=4',
//     ginHabLink: 'https://github.com/Saniokkk',
//     FB_Link: 'https://www.facebook.com/profile.php?id=100002548663025',
//     LN_Link: 'https://www.linkedin.com/in/kashirin-aleksandr-244b49237/',
//     discription: 'Ну ось зробили ще один чудовий проект. Тепер ми стали набагато ближчі до своєї мети. Дякую моїй команді та компанії GoIT за надані знання та досвід.',
//   },
// ];